Added slick page transition animations
Bumped version to v0.4.0

Signed-off-by: AgilePlaya <60707646+AgilePlaya@users.noreply.github.com>

diff --git a/.github/workflows/ci_nextjs_build.yml b/.github/workflows/ci_nextjs_build.yml
--- a/.github/workflows/ci_nextjs_build.yml
+++ b/.github/workflows/ci_nextjs_build.yml
@@ -5,72 +5,74 @@
 name: "[CI] NextJs Build Test"
 
 on:
-  # Runs on pushes targeting the default branch
-  pull_request:
-    branches: [ "main", "main-staging" ]
+    # Runs on pushes targeting the default branch
+    pull_request:
+        branches: ["main", "main-staging"]
 
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
+    # Allows you to run this workflow manually from the Actions tab
+    workflow_dispatch:
 
 # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
 permissions:
-  contents: read
-  pages: write
-  id-token: write
+    contents: read
+    pages: write
+    id-token: write
 
 # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
 # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
 concurrency:
-  group: "test_build"
-  cancel-in-progress: true
+    group: "test_build"
+    cancel-in-progress: true
 
 jobs:
-  # Build job
-  Build_Job:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        node-version: [18.x, 20.x, 22.x]
+    # Build job
+    Build_Job:
+        runs-on: ubuntu-latest
+        strategy:
+            matrix:
+                node-version: [18.x, 20.x, 22.x]
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v4
 
-      - name: Detect package manager
-        id: detect-pm
-        run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+            - name: Detect package manager
+              id: detect-pm
+              run: |
+                  if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+                    echo "manager=yarn" >> $GITHUB_OUTPUT
+                    echo "command=install" >> $GITHUB_OUTPUT
+                    exit 0
+                  elif [ -f "${{ github.workspace }}/package.json" ]; then
+                    echo "manager=npm" >> $GITHUB_OUTPUT
+                    echo "command=ci" >> $GITHUB_OUTPUT
+                    exit 0
+                  else
+                    echo "Unable to determine package manager"
+                    exit 1
+                  fi
 
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ matrix.node-version }}
-          cache: ${{ steps.detect-pm.outputs.manager }}
+            - name: Setup Node
+              uses: actions/setup-node@v4
+              with:
+                  node-version: ${{ matrix.node-version }}
+                  cache: ${{ steps.detect-pm.outputs.manager }}
 
-      - name: Install dependencies
-        run: ${{ steps.detect-pm.outputs.manager }} ${{ steps.detect-pm.outputs.command }}
+            - name: Install dependencies
+              run: |
+                  ${{ steps.detect-pm.outputs.manager }} config set legacy-peer-deps true
+                  ${{ steps.detect-pm.outputs.manager }} ${{ steps.detect-pm.outputs.command }}
 
-      - name: Build with NodeJS
-        run: ${{ steps.detect-pm.outputs.manager }} run build --if-present
+            - name: Build with NodeJS
+              run: ${{ steps.detect-pm.outputs.manager }} run build --if-present
 
-      - name: Check NextJS telemetry status
-        run: npx next telemetry status
+            - name: Check NextJS telemetry status
+              run: npx next telemetry status
 
-      - name: Upload artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: Build-Artifact-${{ matrix.node-version }}
-          path: build
-          compression-level: 9
-          retention-days: 2
+            - name: Upload artifact
+              uses: actions/upload-artifact@v4
+              with:
+                  name: Build-Artifact-${{ matrix.node-version }}
+                  path: build
+                  compression-level: 9
+                  retention-days: 2
